// MetaDSL Examples
// This file contains example MetaDSL scripts for self-bootstrapping

// ========================================
// Example 1: Basic File Operations
// ========================================

// Example: Read a file
read_file('managed/Script.dsl');

// Example: Create a new file with content
write_file(
  'test_output.txt',
  'Hello from MetaDSL!\nThis file was created by the agent itself.'
);

// Example: Modify an existing file
replace_file(
  'test_output.txt',
  'Hello from MetaDSL!',
  'Updated by MetaDSL!',
  false
);

// Example: Delete a file
delete_file('test_output.txt');

// ========================================
// Example 2: Self-Modification
// ========================================

// Example: Add a new function to Script.dsl
replace_file(
  'managed/Script.dsl',
  '// End of script',
  '
    // New function added by MetaDSL
    script(new_auto_feature)params($param)
    {
        nativelog("[dsl] Auto feature executed with param: {0}", $param);
        return(0);
    };

    // End of script
  ',
  true
);

// Example: Modify existing function behavior
replace_file(
  'managed/Script.dsl',
  'nativelog("[dsl] Agent initialized");',
  '
    nativelog("[dsl] Agent initialized - enhanced version");
    nativelog("[dsl] Self-improvement active");
  ',
  true
);

// ========================================
// Example 3: Command Execution
// ========================================

// Example: Execute git status
execute_command('git status', '', '', 0);

// Example: Execute a build command
execute_command('dotnet build ../AgentCore/AgentCore.csproj', '', '', 0);

// ========================================
// Example 4: Hot Reload
// ========================================

// Example: Reload all components
hot_reload('all');

// Example: Reload only Script.dsl
hot_reload('script');

// Example: Reload inject.js
hot_reload('inject');

// ========================================
// Example 5: Complete Self-Update Workflow
// ========================================

// Step 1: Read current configuration
read_file('managed/Script.dsl');

// Step 2: Add new capability
replace_file(
  'managed/Script.dsl',
  'return(0);',
  '
    // Auto-documentation feature
    script(auto_document)params($filePath)
    {
        nativelog("[dsl] Generating documentation for: {0}", $filePath);

        // Read file content
        $content = read_file('managed/Script.dsl');

        // Generate simple documentation
        $doc = "Documentation for: " + $filePath;
        $doc = $doc + "\nGenerated by self-bootstrapping agent\n";

        nativelog("[dsl] Documentation: {0}", $doc);
        return($doc);
    };

    return(0);
  ',
  true
);

// Step 3: Add new API function
replace_file(
  'managed/Script.dsl',
  'BatchCommand.BatchScript.Register',
  '
    // Register new API
    BatchCommand.BatchScript.Register("read_file_text", "read_file_text(path)", new ExpressionFactoryHelper<ReadFileTextExp>());

    BatchCommand.BatchScript.Register
  ',
  true
);

// Step 4: Trigger hot reload to apply changes
hot_reload('script');

// ========================================
// Example 6: Self-Healing Script
// ========================================

// Detect and fix common error patterns
replace_file(
  'managed/Script.dsl',
  'catch (Exception ex)',
  '
    catch (Exception ex)
    {
        nativelog("[dsl] Error caught: {0}", ex.Message);
        // Auto-healing: attempt recovery
        nativelog("[dsl] Attempting auto-recovery...");
    }
  ',
  true
);

// ========================================
// Example 7: Performance Optimization
// ========================================

// Add caching mechanism
replace_file(
  'managed/Script.dsl',
  '// Performance optimization needed here',
  '
    // Performance: Cache frequently used data
    if(@cache_enabled) {
        return(@cache_data);
    }

    // Performance optimization needed here
  ',
  true
);

// ========================================
// Example 8: Self-Monitoring
// ========================================

// Add self-diagnostic capability
replace_file(
  'managed/Script.dsl',
  'return(0);',
  '
    // Self-diagnostic function
    script(self_diagnostic)params()
    {
        nativelog("[dsl] Running self-diagnostic...");
        nativelog("[dsl] AgentCore status: OK");
        nativelog("[dsl] Script status: OK");
        nativelog("[dsl] Inject script status: OK");
        return(0);
    };

    return(0);
  ',
  true
);

// ========================================
// Example 9: Feature Flag System
// ========================================

// Add feature flag support
replace_file(
  'managed/Script.dsl',
  'return(0);',
  '
    // Feature flag management
    script(set_feature_flag)params($feature, $enabled)
    {
        $flagKey = "feature_" + $feature;
        if($enabled == "true") {
            BatchCommand.BatchScript.SetGlobalVariable($flagKey, true);
        } else {
            BatchCommand.BatchScript.SetGlobalVariable($flagKey, false);
        }
        nativelog("[dsl] Feature flag set: {0}={1}", $feature, $enabled);
        return(0);
    };

    return(0);
  ',
  true
);

// ========================================
// Example 10: Complete Auto-Update
// ========================================

// Full self-update sequence
write_file(
  'managed/Script.dsl',
  '
    // Auto-generated by self-bootstrapping agent
    // Generated at: ' + get_current_time() + '

    script(on_init)params()
    {
        nativelog("[dsl] Auto-updated agent initialized");
        return(0);
    }
  '
);

hot_reload('all');

// ========================================
// Notes and Best Practices
// ========================================

// 1. Always test MetaDSL scripts in a safe environment first
// 2. Use version control (git) to easily rollback changes
// 3. Backup important files before modification
// 4. Monitor logs for errors during MetaDSL execution
// 5. Start with simple modifications, then move to complex ones
// 6. Document your MetaDSL scripts for future reference

// ========================================
// Debugging Tips
// ========================================

// If MetaDSL execution fails:
// 1. Check file paths are correct
// 2. Verify old_text exactly matches content (case-sensitive)
// 3. Ensure proper quoting in parameters
// 4. Review error messages in agent logs
// 5. Test with small changes first

// Example with error handling:
// read_file('test.txt');
// If this fails, check if file exists and path is correct
